"""empty message

Revision ID: 079ddf4e08eb
Revises: f4e19618dd7a
Create Date: 2026-09-02 19:29:05.045251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079ddf4e08eb'
down_revision = 'f4e19618dd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
